name: CI

on:
  push:
    branches:
      -  KAN-1-feature-ms-GiovanniBahamondes-mensaje

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Clonacion de codigo
        uses: actions/checkout@v4

      - name: Stepup Java JKD
        uses: actions/setup-java@v4.2.1
        with:
         java-version: '8'
         distribution: 'temurin'
         cache: maven
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Pruebas Unitarias
        run: mvn clean verify
      
      - name: Setup Java JDK for SonarCloud
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Analisis de sonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=devops-final-project_java-ms-final

      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          scanMetadataReportFile: target/sonar/report-task.txt